DROP TABLE IF EXISTS People;
PRAGMA encoding = 'utf-8';

.mode csv
.import $csv_path People
ALTER TABLE People DROP COLUMN "?";
ALTER TABLE People DROP COLUMN "Unnamed: 0";
ALTER TABLE People DROP COLUMN "item.type";
ALTER TABLE People DROP COLUMN "itemLabel.xml:lang";
ALTER TABLE People DROP COLUMN "itemLabel.type";
ALTER TABLE People DROP COLUMN "place_of_birthLabel.xml:lang";
ALTER TABLE People DROP COLUMN "place_of_birthLabel.type";
ALTER TABLE People DROP COLUMN "imageLabel.type";
ALTER TABLE People DROP COLUMN "imageLabel.value";
ALTER TABLE People DROP COLUMN "sex_or_genderLabel.xml:lang";
ALTER TABLE People DROP COLUMN "sex_or_genderLabel.type";
ALTER TABLE People DROP COLUMN "instance_ofLabel.xml:lang";
ALTER TABLE People DROP COLUMN "instance_ofLabel.type";
ALTER TABLE People DROP COLUMN "instance_ofLabel.value";
ALTER TABLE People DROP COLUMN "country_of_citizenshipLabel.xml:lang";
ALTER TABLE People DROP COLUMN "country_of_citizenshipLabel.type";
ALTER TABLE People DROP COLUMN "occupationLabel.xml:lang";
ALTER TABLE People DROP COLUMN "occupationLabel.type";
ALTER TABLE People DROP COLUMN "Commons_categoryLabel.type";
ALTER TABLE People DROP COLUMN "Commons_categoryLabel.value";
ALTER TABLE People DROP COLUMN "date_of_birthLabel.type";
ALTER TABLE People DROP COLUMN "family_nameLabel.xml:lang";
ALTER TABLE People DROP COLUMN "family_nameLabel.type";
ALTER TABLE People DROP COLUMN "given_nameLabel.xml:lang";
ALTER TABLE People DROP COLUMN "given_nameLabel.type";
ALTER TABLE People DROP COLUMN "languages_spoken__written_or_signedLabel.xml:lang";
ALTER TABLE People DROP COLUMN "languages_spoken__written_or_signedLabel.type";
ALTER TABLE People DROP COLUMN "name_in_native_languageLabel.type";
ALTER TABLE People DROP COLUMN "ISNILabel.type";
ALTER TABLE People DROP COLUMN "ISNILabel.value";
ALTER TABLE People DROP COLUMN "signatureLabel.type";
ALTER TABLE People DROP COLUMN "signatureLabel.value";
ALTER TABLE People DROP COLUMN "described_by_sourceLabel.xml:lang";
ALTER TABLE People DROP COLUMN "described_by_sourceLabel.type";
ALTER TABLE People DROP COLUMN "described_by_sourceLabel.value";
ALTER TABLE People DROP COLUMN "motherLabel.xml:lang";
ALTER TABLE People DROP COLUMN "motherLabel.type";
ALTER TABLE People DROP COLUMN "spouseLabel.xml:lang";
ALTER TABLE People DROP COLUMN "spouseLabel.type";
ALTER TABLE People DROP COLUMN "fatherLabel.xml:lang";
ALTER TABLE People DROP COLUMN "fatherLabel.type";
ALTER TABLE People DROP COLUMN "religion_or_worldviewLabel.xml:lang";
ALTER TABLE People DROP COLUMN "religion_or_worldviewLabel.type";
ALTER TABLE People DROP COLUMN "topic_s_main_categoryLabel.xml:lang";
ALTER TABLE People DROP COLUMN "topic_s_main_categoryLabel.type";
ALTER TABLE People DROP COLUMN "topic_s_main_categoryLabel.value";
ALTER TABLE People DROP COLUMN "Commons_galleryLabel.type";
ALTER TABLE People DROP COLUMN "Commons_galleryLabel.value";