repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        types_or: [ "python", "pyi", "jupyter" ]
        args: [ "--fix" ]
      - id: ruff-format
