exclude = [
    "__pycache__",
    ".ipynb_checkpoints",
    "*.egg-info",
    ".idea",
    ".DS_Store",
    ".vscode",
    "data",
    "output",
    ".history",
    "*.zip",
    "venv",
    ".coverage",
    "htmlcov",
    "html",
    "dist/*",
    "profile.html",
    "profile.json",
    "*.log",
]

line-length = 90
indent-width = 4
target-version = "py310"

[lint]
select = ["E4", "E7", "E9", "F"]
ignore = []
fixable = ["ALL"]
unfixable = []

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
