name:                  Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - mkdocs_branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
   
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip "setuptools>=62.4"

    - name: Build docs
      run: |
        make mkdocs

    - name: Upload docs
      uses: actions/upload-artifact@v4
      with:
        name: mkdocs-site
        path: docs/

  publish:
    needs: build-deploy
    name: Deploy to private site
    uses: probcomp/gen-website-private/.github/workflows/publish_private_website.yml@main
    with:
      artifact: mkdocs-site