name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - mkdocs_branch
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip "setuptools>=62.4"

    - name: Build docs
      run: |
        make mkdocs-no-vllm

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
