name:                  Linter

on:
  push:
    branches:          [main]
  pull_request:
    branches:          [main]

jobs:
  run_tests:
    runs-on:           ubuntu-latest
    steps:
      # - name:          free disk space
      #   uses:          jlumbroso/free-disk-space@v1.3.1
      - name:          checkout repo
        uses:          actions/checkout@v3.0.0
        with:
          fetch-depth: 1
      - name:          run linter
        run: |
                       python -m venv venv
                       source venv/bin/activate
                       pip install --upgrade pip "setuptools>=62.4"
                       make ruff-no-vllm
